# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                      Input Configuration                    ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# Input wiki https://wiki.hyprland.org/0.45.0/Configuring/Variables/#input

input {
    numlock_by_default = true

    follow_mouse = 0 # 0|1|2|3
    sensitivity = 0

    touchpad {
        natural_scroll = true
    }
}

device {
    name = ugreen-mouse-1
    accel_profile = flat
}

device {
    name = ugreen-mouse-consumer-control-1
    accel_profile = flat
}
